"""Report generator — builds HTML from Jinja2 template and renders to PDF via QPrinter."""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import datetime

from jinja2 import Template

logger = logging.getLogger(__name__)


@dataclass
class ReportData:
    """Data container for report generation."""
    title: str = "Portfolio Report"
    date: str = ""
    portfolio_name: str = "Portfolio"
    weights: dict[str, float] | None = None
    metrics: dict[str, float] | None = None
    executive_summary: str | None = None
    chart_images: dict[str, str] = field(default_factory=dict)  # section -> data_uri
    sections: list[str] = field(default_factory=list)

    def __post_init__(self):
        if not self.date:
            self.date = datetime.now().strftime("%B %d, %Y")


# ── HTML Template ────────────────────────────────────────────────────

HTML_TEMPLATE = Template("""\
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
    @page { margin: 15mm; }
    * { box-sizing: border-box; }
    body {
        font-family: 'Segoe UI', 'Inter', sans-serif;
        background: #0a0e14;
        color: #e6edf3;
        font-size: 10pt;
        line-height: 1.5;
        margin: 0;
        padding: 0;
    }
    .header {
        border-bottom: 2px solid #00d4ff;
        padding-bottom: 12px;
        margin-bottom: 20px;
    }
    .header h1 {
        color: #00d4ff;
        font-size: 22pt;
        margin: 0 0 4px 0;
        letter-spacing: 2px;
    }
    .header .subtitle {
        color: #8b949e;
        font-size: 10pt;
    }
    h2 {
        color: #00d4ff;
        font-size: 13pt;
        border-bottom: 1px solid #30363d;
        padding-bottom: 6px;
        margin-top: 24px;
    }
    .summary-box {
        background: #161b22;
        border: 1px solid #30363d;
        border-radius: 6px;
        padding: 14px;
        margin: 12px 0;
        line-height: 1.6;
    }
    table {
        width: 100%;
        border-collapse: collapse;
        margin: 10px 0;
        font-size: 9pt;
    }
    th {
        background: #161b22;
        color: #00d4ff;
        text-align: left;
        padding: 6px 10px;
        border-bottom: 1px solid #30363d;
        font-weight: 600;
    }
    td {
        padding: 5px 10px;
        border-bottom: 1px solid #1c2333;
    }
    tr:nth-child(even) { background: #0d1117; }
    .metric-value {
        font-family: 'JetBrains Mono', 'Consolas', monospace;
        color: #f0f6fc;
    }
    .positive { color: #00ff88; }
    .negative { color: #ff4757; }
    .chart-container {
        margin: 12px 0;
        text-align: center;
    }
    .chart-container img {
        max-width: 100%;
        border: 1px solid #30363d;
        border-radius: 4px;
    }
    .footer {
        margin-top: 30px;
        padding-top: 10px;
        border-top: 1px solid #30363d;
        color: #6e7681;
        font-size: 8pt;
        text-align: center;
    }
</style>
</head>
<body>

<div class="header">
    <h1>{{ title }}</h1>
    <div class="subtitle">{{ portfolio_name }} &mdash; {{ date }}</div>
</div>

{% if "executive_summary" in sections and executive_summary %}
<h2>Executive Summary</h2>
<div class="summary-box">
    {{ executive_summary }}
</div>
{% endif %}

{% if "holdings" in sections and weights %}
<h2>Portfolio Holdings</h2>
<table>
    <tr><th>Symbol</th><th>Weight</th><th>Bar</th></tr>
    {% for sym, w in sorted_weights %}
    <tr>
        <td><b>{{ sym }}</b></td>
        <td class="metric-value">{{ "%.2f" | format(w * 100) }}%</td>
        <td>
            <div style="background:#0a3d5c; width:{{ (w * 300)|int }}px; height:10px;
                         border-radius:2px; display:inline-block;"></div>
        </td>
    </tr>
    {% endfor %}
</table>
{% endif %}

{% if "metrics" in sections and metrics %}
<h2>Performance Metrics</h2>
<table>
    <tr><th>Metric</th><th>Value</th></tr>
    {% for name, val in metrics.items() %}
    <tr>
        <td>{{ name | replace("_", " ") | title }}</td>
        <td class="metric-value {% if val is number and val > 0 %}positive{% elif val is number and val < 0 %}negative{% endif %}">
            {% if val is number %}{{ "%.4f" | format(val) }}{% else %}{{ val }}{% endif %}
        </td>
    </tr>
    {% endfor %}
</table>
{% endif %}

{% for section_name, data_uri in chart_images.items() %}
{% if section_name in sections or "charts" in sections %}
<h2>{{ section_name | replace("_", " ") | title }}</h2>
<div class="chart-container">
    <img src="{{ data_uri }}" alt="{{ section_name }}">
</div>
{% endif %}
{% endfor %}

<div class="footer">
    Generated by Meridian Portfolio Terminal &mdash; {{ timestamp }}
</div>

</body>
</html>
""")


def render_html(data: ReportData) -> str:
    """Render the report HTML from the template and data."""
    sorted_weights = []
    if data.weights:
        sorted_weights = sorted(data.weights.items(), key=lambda x: -x[1])
        sorted_weights = [(s, w) for s, w in sorted_weights if w > 0.001]

    return HTML_TEMPLATE.render(
        title=data.title,
        date=data.date,
        portfolio_name=data.portfolio_name,
        weights=data.weights,
        sorted_weights=sorted_weights,
        metrics=data.metrics,
        executive_summary=data.executive_summary,
        chart_images=data.chart_images,
        sections=data.sections,
        timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
    )


def generate_pdf(html: str, output_path: str) -> bool:
    """Render HTML to a PDF file using QPrinter.

    Must be called from the main GUI thread.

    Returns True on success.
    """
    try:
        from PySide6.QtGui import QTextDocument
        from PySide6.QtPrintSupport import QPrinter
        from PySide6.QtCore import QMarginsF

        printer = QPrinter(QPrinter.PrinterMode.HighResolution)
        printer.setOutputFormat(QPrinter.OutputFormat.PdfFormat)
        printer.setOutputFileName(output_path)
        printer.setPageMargins(QMarginsF(15, 15, 15, 15))

        doc = QTextDocument()
        doc.setHtml(html)
        doc.setPageSize(printer.pageRect(QPrinter.Unit.Point).size())
        doc.print_(printer)

        logger.info("Report PDF generated: %s", output_path)
        return True

    except Exception as e:
        logger.error("Failed to generate PDF: %s", e, exc_info=True)
        return False
